# golangci-lint configuration

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
    - e2e
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - test/mocks

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - prealloc
    - misspell
    - lll
    - unparam
    - nakedret
    - gocritic
    - revive
    - unconvert
    - bodyclose
    - noctx
    - sqlclosecheck
    - nolintlint
    - whitespace
    - goprintffuncname
    - gomodguard
    - godot
    - nestif

linters-settings:
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gosec:
    excludes:
      - G104
      - G304
  
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: superfluous-else
      - name: unreachable-code

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - goconst
        - gocyclo
        - gocognit
    
    - path: test/
      linters:
        - gosec
        - errcheck
    
    - path: cmd/
      linters:
        - gocyclo
        - gocognit
    
    - path: "mock_"
      linters: [dupl, gosec, goconst]
    
    - text: "at least one file in a package should have a package comment"
      linters:
        - revive
    
    - text: "should have a package comment"
      linters:
        - revive